### ISSUE TITLE
Connection to semantic turkey server failed

### ISSUE THREAD

**Issue by mhabsaoui** [nvdk/docker-vocbench#1]
Hi,

i succeded in running the docker-compose containers, and i have this so far:

`CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS              PORTS                     NAMES
dbb8e90b3891        dockervocbench_vocbench      "catalina.sh run"        47 minutes ago      Up 47 minutes       0.0.0.0:10140->8080/tcp   dockervocbench_vocbench_1
a5db0c75f547        dockervocbench_vocbench-st   "./karaf server"         47 minutes ago      Up 47 minutes       1979/tcp                  dockervocbench_vocbench-st_1
3d24cda8fd8c        openuniversity/sesame        "/run.sh"                47 minutes ago      Up 47 minutes       0.0.0.0:10150->8080/tcp   dockervocbench_vocbench-sesame_1
785cf0d453f0        mariadb                      "docker-entrypoint.sh"   47 minutes ago      Up 47 minutes       3306/tcp                  dockervocbench_vocbench-db_1
`

Now, when trying the "Quick Test Drive", with the popup to create a new project ==> it says connection to semantic turkey server failed, wheras it is already  started :/

![capture](https://cloud.githubusercontent.com/assets/18755135/26095431/dddcd19c-3a1d-11e7-88ce-97e3875da1bb.PNG)

PS: 
- I've checked the BASE URI given in the Quick Test Drive, but 404 error. So the good URL should be  http://www.fao.org/land-water/    ==>  Right ?

- 

> It is assumed that ST Server has been started, if it has not, then start it now

I've tried to manually restart the ST Server (inside or outside the ST container with docker exec ...), but i had a "permission denied" :/

`$ docker exec dockervocbench_vocbench-st_1 /semantic-turkey/semanticturkey-0.11/bin/st_server_run
rpc error: code = 2 desc = oci runtime error: exec failed: exec: "/semantic-turkey/semanticturkey-0.11/bin/st_server_run": permission denied`

thanks for help.

**Comment by mhabsaoui** [comment]
Well it needed the creation of a new instance of ST with "st, 1979" parameters so it can access the ST inside the docker container...
Even if infos written on readme, not clear where/how to do it though.

The mounted volumes ./upload on vocbench / ST were made to avoid failure of data import (*.nt files ) through user interface => the docker containes need to exchange data (from vocbench to ST / Sesame)

**Comment by nvdk** [comment]
Thanks for clarifying this. Feel free to send me a pull request to improve
the docker image

**Comment by mhabsaoui** [comment]
I close this issue as this point is solved.
